Feature/extend history
SIIS-Ltd/Curiosity.Migrations pull request #13
Opened 2020-02-07 15:43 UTC by anri-vin

1. History table creation query updated.
2. Updated retrieval of last migration version.
3. Write migration comment to DB.
4. Fix tests to use updated methods.

2020-02-07 15:44 UTC, anri-vin commented
Closes #8

2020-02-10 10:29 UTC, Markeli requested changes

2020-02-10 10:29 UTC, Markeli commented on src/Curiosity.Migrations.PostgreSQL/PostgreDbProvider.cs
> +                         @"
Maybe, we need to grant access to the owner like in scripts?

2020-02-10 10:37 UTC, Markeli approved these changes

2020-02-10 10:37 UTC, merged